import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../Components/Footer";
import Nav from "../Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gradient-to-b from-slate-800 to-blue-600">
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
